### ISSUE TITLE
`FromJSON` and `ToJSON` don't roundtrip for `Double`

### ISSUE THREAD

**Issue by NorfairKing** [haskell/aeson#679]
```
1) Test.Validity.Aeson, JSON Double (unchecked), decode :: Data.ByteString.Lazy.ByteString -> Either String Double, ensures that encode and decode are inverses for "unchecked Double"'s
       Falsifiable (after 12 tests):
         Infinity
       Decoding succeeded, but the decoded value
       NaN
       differs from expected decoded value
       Infinity
       'encode' encoded it to the json
       "null"
```

**Comment by NorfairKing** [comment]
It's also broken the different values of `NaN` if you ignore that NaN /= NaN` holds.

**Comment by Lysxia** [comment]
I wonder how this should be fixed. [This ECMA spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) just says:

> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not
permitted.

Looking around, I can find no consensus about how to handle this, because at some point you'll want to encode a double which may be one of these special values

https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

Though silently encoding to `null` seems a pretty common choice to avoid throwing exceptions.

https://github.com/capnproto/capnproto/issues/261
https://github.com/graphite-project/graphite-web/issues/813

If we really want roundtripping for infinity values, maybe we should encode them as strings.

**Comment by NorfairKing** [comment]
@Lysxia I'm fine with just throwing up our hands and saying "here are al the links to related projects that are similarly broken as intended" by the way. Just wanted to point it out because it showed up in my test suite.

**Comment by phadej** [comment]
The issue is *known*.

https://github.com/bos/aeson/blob/master/tests/SerializationFormatSpec.hs#L198-L206

**Comment by quasicomputational** [comment]
I agree that the quote from the spec isn't the final word and stringy encoding would make sense. It's discussing JSON's concept of numbers; there's no rule that applications can't interpret, e.g., the string 'NaN' as NaN, just that a JSON processor has to reject NaN as a numeric value. Obviously this means that we won't inter-operate with anything that doesn't use the same conventions, but we're currently not able to inter-operate with anything that needs NaNs and infinities transmitted anyway.

**Comment by phadej** [comment]
As we **can** differentiate between

```haskell
λ> signum (-0.0 :: Double)
-0.0
λ> signum (0.0 :: Double)
0.0
```

how we would encode `-0.0`?

`Double` and equality makes my head hurt. I guess encoding infinities as `"inf"`, `"ninf"` and leaving `null` for `NaN` won't break many users.

**Comment by NorfairKing** [comment]
Closing this as "wontfix because double is not encodable as a javascript number on purpose".

**Comment by brandon-leapyear** [comment]
> The issue is _known_.
> 
> https://github.com/bos/aeson/blob/master/tests/SerializationFormatSpec.hs#L198-L206

Here's a permalink for this referenced link: https://github.com/haskell/aeson/blob/3bd3c6d788df857a88260f0f0bef6ec49b601905/tests/SerializationFormatSpec.hs#L198-L206

Seems like this was fixed in `aeson-2`: https://github.com/haskell/aeson/commit/615054e01d26db719552bffb4ac851a9fe809542, for those coming in late. Thanks @phadej!
