### ISSUE TITLE
Missing `contents` field doesn't decode to Nothing when target type is Maybe

### ISSUE THREAD

**Issue by maxhallinan** [haskell/aeson#782]
I'm not sure if this is intended behavior. Here is a small example

```haskell
module Foo where

import Prelude
import Data.Aeson
import Data.Aeson.TH

data Foo = Foo { foo :: Maybe Bool }
  deriving stock Show
$(deriveJSON defaultOptions ''Foo)

data Bar = Bar (Maybe Bool) | Baz Bool
  deriving stock Show
$(deriveJSON defaultOptions ''Bar)
```

```
ghci> decode "{\"tag\": \"Foo\"}" :: Maybe Foo
Just (Foo {foo = Nothing})
ghci> decode "{\"tag\": \"Bar\"}" :: Maybe Bar
Nothing
ghci> decode "{\"tag\": \"Bar\", \"contents\": false}" :: Maybe Bar
Just (Bar (Just False))
```

I expected that `decode "{\"tag\": \"Bar\"}" :: Maybe Bar` would decode to `Bar Nothing` just as `decode "{\"tag\": \"Foo\"}"` decodes to `Foo {foo = Nothing}`. If this is intentional, what is the difference?

**Comment by Lysxia** [comment]
`Foo` is a record, `Bar` is not. See [`TaggedObject`](https://hackage.haskell.org/package/aeson-1.5.1.0/docs/Data-Aeson.html#t:SumEncoding):

>  If the constructor is a record the encoded record fields will be unpacked into this object.

`Bar` is not a record, so it uses the `{"tag":_,"contents":_}` encoding which is oblivious to the types of the constructor fields.

**Comment by maxhallinan** [comment]
>Foo is a record, Bar is not. 

The question is why is the behavior different? It's not a nice user experience.

**Comment by bergmark** [comment]
As a side note, if you use `eitherDecode` instead of `decode` you will probably have an easier time debugging.

Maybe it could work to relax parsing so that `{"tag": "Bar"}` is treated the same as `{"tag": "Bar", contents: [null] }` (a null for every field)?

A lot of the time I end up customizing the instances for sum types since the default is often not what I want, but changing the actual default now may lead to a lot of silent breakages downstream so it's a tricky thing to do.
