### ISSUE TITLE
Possible DOS due to hash collision

### ISSUE THREAD

**Issue by TomMD** [haskell/aeson#864]
As detailed in [a blog](https://cs-syd.eu/posts/2021-09-11-json-vulnerability?source=github_issue), Aeson is susceptible to DOS if given maliciously-crafted JSON.  This is likely a tired conversation for many developers, but with the public posting today it seems good to have a public issue tracking the discussion and resolution.

**Comment by NorfairKing** [comment]
Author here: Happy to help with this.

**Comment by phadej** [comment]
Indeed, it's old and known problem. See e.g. https://oleg.fi/gists/posts/2021-05-19-dont-default-to-hashmap.html

Yet, I'm not keen at changing `Value`, but rather would skip `Value` in decoding pipeline entirely. That would allow people e.g. process key-value pairs on order (if it matters for them), deal with duplicate keys (again, if it matters), possibly work with as-written values of number literals etc.

**Comment by NorfairKing** [comment]
> Indeed, it's old and known problem. See e.g. https://oleg.fi/gists/posts/2021-05-19-dont-default-to-hashmap.html

With all due respect, that makes this worse, not better.

> Yet, I'm not keen at changing Value, but rather would skip Value in decoding pipeline entirely.

That's a _much_ bigger breaking change and would make it entirely new library.
We have played around with this idea by making the equivalent of optparse-applicative, but for json parsing without an intermediate type.
That approach has different tradeoffs and can be cool, but it doesn't solve the problem at hand in `aeson` right now.

**Comment by TomMD** [comment]
@NorfairKing In the post you indicated a rejected PR, could you link that here now that the issue is publicly discussed?

@phadej Among the proposed paths forward, is there a short-term solution you'd be in favor of? This issue deserves a short term fix, even if it isn't the desired end state.

**Comment by NorfairKing** [comment]
> @NorfairKing In the post you indicated a rejected PR, could you link that here now that the issue is publicly discussed?

It's linked in the post but here's the link again: https://github.com/haskell-unordered-containers/unordered-containers/pull/217

**Comment by phadej** [comment]
@TomMD:
- Introduce `Data.Aeson.Object` module with an`Object` opaque `newtype`(fromList, toList, member), maybe `TextMap v` would be simpler to avoid circular dependencies.
- Add a manual flag to switch between `Map` to `HashMap`- the internals shouldn't matter if they are hidden behind opaque `TextMap`.

**Comment by lehins** [comment]
Just a suggestion, but maybe `Blake2b_64`/`Blake2s_32` here is a good solution. Blake2b_256 is much faster than SHA-256, but maybe doing Blake2b_64 is even faster than just cropping 256bit hash to 64 bits.

I have suspicion that cooking up collisions for Blake2 (even with a small digest size) would be prohibitively expensive for the purpose of DoS attack

**Comment by konsumlamm** [comment]
Another solution could be using some map data structure specialized to `Text` keys (something like a trie, for example [`text-trie`](https://hackage.haskell.org/package/text-trie) (although I have no idea how performant that implementation is) or a ternary search tree). This would of course be a breaking change, but so would using `Data.Map` (and it could be hidden behind a `newtype`, as suggested by @phadej).

This would have the advantage (apart from not being susceptible to hash DoS attacks obviously) that it doesn't (potentially) cause lots of string comparisons (this could be a problem with `Data.Map` if lots of the keys share the same prefix). Disclaimer: I didn't run any benchmarks, so I'm not sure if this would actually be faster in practice than using `Data.Map` (which has been extensively optimized after all), especially since `text-2.0` will apparently use a more efficient `compare` implementation (see [here](https://www.reddit.com/r/haskell/comments/pm7rcr/cs_syd_json_vulnerability_in_haskells_aeson/hcgawtm?utm_source=share&utm_medium=web2x&context=3)).

**Comment by phadej** [comment]
@konsumlamm my solution is to make `Object` opaque.Then people are free to experiment with different representations, secure, fast, both, neither.

**Comment by phadej** [comment]
More concretely, something like: https://github.com/haskell/aeson/compare/textmap

The rest is just `H.foo` -> `TM.foo` all over  the place. (And something smart to make `FromJSONKeyCoerce` work)

**Comment by Boarders** [comment]
I'm going to try and push that through @phadej.

**Comment by joelmccracken** [comment]
@Boarders @phadej I was just considering that too. Please flag me if you could use any help.

**Comment by Boarders** [comment]
@phadej What did you have in mind with the `Lift` instance, is there an easy way to write it?

**Comment by TravisCardwell** [comment]
> That would allow people e.g. process key-value pairs on order (if it matters for them), ...

I often work with YAML files where the order of object properties is important.  Humans edit YAML files, and a logical order of object properties maximizes the usability.  I do not know of a way to do this in Haskell using existing libraries, and this issue unfortunately sometimes results in having to use a different language.

This comment is in agreement with the current direction, but I am adding it as a concrete example of a real-world issue that Oleg's suggestion would resolve, in addition to the hash collision issue.

**Comment by phadej** [comment]
> @phadej What did you have in mind with the `Lift` instance, is there an easy way to write it?

look at the diff, probably something like

```haskell
lift (TextMap m) = [| TextMap (H.fromList . map (first pack) $ m') |]
      where m' = map (first unpack) . H.toList $ m
```

It would be good to first introduce `TextMap`, and only then fiddle with its implementation.

**Comment by piyush-kurur** [comment]
> Just a suggestion, but maybe `Blake2b_64`/`Blake2s_32` here is a good solution. Blake2b_256 is much faster than SHA-256, but maybe doing Blake2b_64 is even faster than just cropping 256bit hash to 64 bits.
> 
> I have suspicion that cooking up collisions for Blake2 (even with a small digest size) would be prohibitively expensive for the purpose of DoS attack

Probably this is relevant

https://github.com/google/highwayhash/issues/28

**Comment by brendanhay** [comment]
I realise the following probably isn't possible because of `(.:)` and friends, but it'd be nicer (IMO) as the lowest common denominator to use [Vector (Text, Value)](https://github.com/ZHaskell/z-data/blob/7270f7325155ac220b0cec321fe2fc8b20deb506/Z/Data/JSON/Value.hs#L73) and avoid `{Hash,}Map` completely. It's more inline with [the spec](https://datatracker.ietf.org/doc/html/rfc7159#page-6) in that it doesn't specify how duplicate keys are handled, preserves the original ordering of the keys, and doesn't tie you to `Ord` or `Hashable`, etc. 

That said, `TextMap` looks like a clear improvement over the status quo. 👍🏽

**Comment by TravisCardwell** [comment]
> it'd be nicer (IMO) as the lowest common denominator (aka default) to use [Vector (Text, Value)](https://github.com/ZHaskell/z-data/blob/7270f7325155ac220b0cec321fe2fc8b20deb506/Z/Data/JSON/Value.hs#L73) and avoid `{Hash,}Map` completely. It's more inline with [the spec](https://datatracker.ietf.org/doc/html/rfc7159#page-6) in that it doesn't specify how duplicate keys are handled, preserves the original ordering of the keys, and doesn't tie you to `Ord` or `Hashable`, etc.

I completely agree with this, as the order issue has been a significant paint point for me with the current implementation.  I brainstormed about [Aeson Object Design](https://www.extrema.is/blog/2021/09/14/aeson-object-design) in my blog.  Here are my ideas in brief, which address the `(.:)` issue.

The type is named `ObjectEntries` to emphasize that it is a list (`Vector`):

```haskell
type ObjectEntries = Vector (Text, Value)
```

For working with other types, an `Object` type class defines the required API:

```haskell
class Object o where
  lookup :: Text -> o -> Maybe Value

(.:) :: (FromJSON a, Object o) => o -> Text -> Parser a

...
```

Instances can be provided for built-in types, and users are free to define instances for other types:

```haskell
instance Object ObjectEntries where
  lookup k = fmap snd . Vector.find ((== k) . fst)

instance Object (HashMap Text Value) where
  lookup = HashMap.lookup

...
```

The "with" function is named `withObjectEntries` to emphasize that it uses the list (`Vector`) by default:

```haskell
withObjectEntries
  :: String
  -> (ObjectEntries -> Parser a)
  -> Value
  -> Parser a
```

Helper functions can be provided to perform conversions to other types:

```haskell
asHashMap
  :: (HashMap Text Value -> Parser a)
  -> ObjectEntries
  -> Parser a
asHashMap f = f . HashMap.fromList . Vector.toList
```

The example from the documentation would be written as follows:

```haskell
instance FromJSON Coord where
  parseJSON = withObjectEntries "Coord" . asHashMap $ \v -> Coord
    <$> v .: "x"
    <*> v .: "y"
```

This allows the user to decide how to implement each instance.  For example, a public API may prioritize security while an internal or administrative API may prioritize performance.

`Generic` instances could have a suitable default and provide a compile-time flag that allows users to select an alternative, much like the current fix.

**Comment by brendanhay** [comment]
For my own codebases I'm not convinced that `(.:)` introducing a linear scan by way of `Vector.find` would even be slower, at least, as the deserialisation routines (for say, a record) never perform repeated lookup of the same object key. As mentioned in the `Z-Data` code I linked above you're probably paying more to materialise a `{Hash,}Map` than what the linear scan for a single key introduces? It would naturally require actual benchmarks to prove that I am not, in fact, a moron for claiming this.

**Comment by phadej** [comment]
Isn't this issue about supposedly O(1) operation degenerating to O(n) (i.e. linear)...

**Comment by TravisCardwell** [comment]
> Isn't this issue about supposedly O(1) operation degenerating to O(n) (i.e. linear)...

Indeed.  (The DoS vulnerability is in the *construction* of the `HashMap`.  Without collision, `fromList` is `O(n log n)` which is practically `O(n)` with a high base.  With collisions, however, each insertion becomes linear, resulting in quadratic performance.)

The current fix allows users to *globally* choose between `Map` and `HashMap` using a flag.  My suggestion provides a way for users to choose which data structure to use *for each instance*, using the flag to set the default for automatic (`Generic`) instances.

In some cases, it would even be possible to use the list (better than `Vector` for conversion) length to mitigate attacks.  For example, consider an API that uses 10 properties.  If the length of the list is above a certain threshold (10 for a strict API), an error could be returned.  Otherwise, the `HashMap` could be constructed and used as usual.  This would allow users to mitigate attacks while keeping the performance of `HashMap`, with only the additional cost of determining the length of the list (one time `O(n)`).  (If the length can be calculated as the JSON is parsed, then there would be no addional cost.)

Would delaying the construction of the (`Hash`)`Map` until `parseJSON` be problematic?  If the goal is to minimize API change, the `withObject` function could do the conversion to `HashMap` and keep the same type, while users can use the constructor (or new API functions) to access the list/`Vector` when necessary, in order to use `Map` for example.

Thank you very much for your time and patience.

**Comment by enobayram** [comment]
Just wanted to chime in that I agree it'll be great for the Haskell ecosystem if whatever solution comes out of this discussion lets us keep the order of JSON object properties. Regardless of how wrong it may be to rely on the order of the properties, many tools and standards still do it, and it's a nightmare to work with them using Haskell. Feels suddenly like the entire ecosystem is taken away from you (i.e. not only `aeson` itself, but all the downstream packages that expose a convenient interface over `aeson`). I find it very unfortunate that this opinionated treatment of the object properties is baked so deeply into Haskell's de-facto standard package for working with JSON.

**Comment by TravisCardwell** [comment]
> For my own codebases I'm not convinced that `(.:)` introducing a linear scan by way of `Vector.find` would even be slower, at least, as the deserialisation routines (for say, a record) never perform repeated lookup of the same object key.  As mentioned in the `Z-Data` code I linked above you're probably paying more to materialise a `{Hash,}Map` than what the linear scan for a single key introduces? It would naturally require actual benchmarks to prove that I am not, in fact, a moron for claiming this.

I ended up running some benchmarks ([blog entry][], [code][]).

[blog entry]: <https://www.extrema.is/blog/2021/09/18/aeson-object-design-part-4>
[code]: <https://github.com/ExtremaIS/www.extrema.is-code/tree/main/blog/2021-09-18-aeson-object-design-part-4>

On my laptop:

* Lists, `Map`, and `HashMap` have similar performance for small objects.  (See the chart in the blog entry and/or the CSV file in the repo.)
* Lists marginally outperformed `HashMap` for objects with 17 or fewer pairs.
* Lists marginally outperformed `Map` for objects with 40 or fewer pairs.
* `Map` marginally outperformed `HashMap` for objects with 10 or fewer pairs.
* `Vector` performance was considerably worse than all that of other types.

In the context of the current fix, using `Map` should *not* result in decreased performance when dealing with small objects.

**Comment by tfausak** [comment]
@TravisCardwell: Did you run those benchmarks with `stack script` as [this](https://github.com/ExtremaIS/www.extrema.is-code/blob/4ee035a32cd5e7052c190c2258d0456ad6bc5301/blog/2021-09-18-aeson-object-design-part-4/bench.hs#L3) suggests? If so, your script was effectively interpreted with `runghc` rather than compiled with `ghc` and then run. [The docs](https://docs.haskellstack.org/en/stable/GUIDE/#just-in-time-compilation) say that if you want to compile with `ghc -O0` you can pass `--compile` and if you want to compile with `ghc -O1` you can pass `--optimize`. 

I wouldn't expect `Vector` to be slower than `[]`, and I especially wouldn't expect looking up about 40 keys to take 200 microseconds. I wrote [my own benchmarks](https://gist.github.com/tfausak/33364b81dff41316273df551814b5a8e/1d00c004566a32c8423a658d1be9b0c3e4ce985b) and got these results (note this is a log-log plot):

![output](https://user-images.githubusercontent.com/408753/133892169-a477fc00-e3a1-48dd-a1a9-c0bbaf09f518.png)

Once you get to n=32, `HashMap`s are the fastest. `InsOrd` is slower by a constant factor since it has to track the order of the keys. After n=64, `Map.Lazy` is the next fastest with `Map.Strict` just behind. `ZVector` and `Vector` are quite a bit slower, and the `List` is slower still. Looking at smaller numbers, at n=16 the vectors are the fastest. At n=2 `List` edges out `Vector`, and at n=0 `List` is the fastest, which makes sense because it doesn't have any associated startup costs. 

My takeaway is that you should basically never use `List`, `Vector` is pretty good until you get more than 32 elements, and `Map` is worse than `HashMap` but not by much.

**Comment by TravisCardwell** [comment]
> Did you run those benchmarks with `stack script` as this suggests? If so, your script was effectively interpreted with `runghc` rather than compiled with `ghc` and then run. The docs say that if you want to compile with `ghc -O0` you can pass `--compile` and if you want to compile with `ghc -O1` you can pass `--optimize`.

Indeed I did!  Thank you *very much* for catching that!  I have updated my code and blog entry to fix the mistake.  I also updated the stats in my comment above to make sure people are not misled by the problematic stats.

Thanks for sharing your benchmark code.  I look forward to using [gauge][] in the future!

[gauge]: <https://hackage.haskell.org/package/gauge>

> My takeaway is that you should basically never use `List`, `Vector` is pretty good until you get more than 32 elements, and `Map` is worse than `HashMap` but not by much.

That sounds good.  On my (old and slow) laptop, `HashMap` is better than `Vector` from 18 pairs, as the performance is system-dependent.

**Comment by ketzacoatl** [comment]
> Indeed, it's old and known problem.

@phadej, if it's an old and known problem, why hasn't it been resolved? Is it too difficult? Too time-consuming? Not enough interest? Not in agreement there is a problem?

**Comment by hasufell** [comment]
If anyone has an API-compatible fork that fixes this issue, please let me know. I'll replace all my uses of aeson with it, even if performance is 10 times worse.

**Comment by phadej** [comment]
`aeson-2.0.0.0` with `ordered-keymap` flag is released

**Comment by NorfairKing** [comment]
@phadej, Do I understand that this vulnerability is still there by default? 

https://github.com/haskell/aeson/blob/4ad6b40b4d1ee7740979afa4411c4d56cd5ac4bf/aeson.cabal#L62-L67

**Comment by phadej** [comment]
I changed the default of `keymap-ordered` in 2.0.1.0: https://hackage.haskell.org/package/aeson-2.0.1.0

Though there is no guarantee it won't be changed again: that's the point of it being internal. If it is important, please pin the flag explicitly in your `cabal.project` / `stack.yaml` / ...

**Comment by ketzacoatl** [comment]
@phadej, for us laymen, can you explain how this is resolved and what level of certainty we can place in the solution?

**Comment by phadej** [comment]
@ketzacoatl upgrade to `aeson-2.0.1.0` or later.

**Comment by ketzacoatl** [comment]
@phadej, thank you for clarifying!

Are there tests that exist or could be added to this package as a regression test or otherwise help us confirm this is resolved?

**Comment by Lysxia** [comment]
@ketzacoatl What's a good way to test this? We could generate colliding inputs and make sure that the resulting map gets constructed in reasonable time, but that only prevents reverting back to unordered-containers specifically, doesn't that seem overly narrow?

If the lesson learned is "don't use vulnerable hashmaps" I think enough noise was made about this issue to make maintainers vigilant for years to come at least as far as aeson is concerned. I'm unsure about this. I could imagine abusing this line of thinking to justify not testing for any bugs, but at the same time I'm not convinced this issue in particular is one that can easily be tested against.

**Comment by phadej** [comment]
Why no curve? To test pass the curve should be e.g. n log n with some confidence. It is easy to make a test which will report true negatives, but we want a test which doesn't report false positives, i.e. doesn't tell that everything is ok when it isn't.

**Comment by ulysses4ever** [comment]
I think @phadej wants to test a stronger hypothesis to find out which asymptotics we are in: linearifmic or quadratic. But @Lysxia makes a (perfectly valid imo) point that a much easier test -- to catch a difference between the two asymptotics (e.g. with explicit `keymap-ordered` and with implicit) -- perfectly suffices: for large enough data you will have a large enough difference to cover for any possible noise on CI machines.

**Comment by phadej** [comment]
@ulysses4ever but we have only one implementation at the time to test, there is nothing to compare to.

Maybe I'm failing to explain, so I'd welcome the patch of your suggestions, so we can discuss something concrete.

**Comment by Lysxia** [comment]
> but we have only one implementation at the time to test, there is nothing to compare to.

I could be misunderstanding you, but like all regression tests, I thought the point is to distinguish the implementation before and the implementation after the bug was fixed.

@NorfairKing Your opinion would be valuable on this. Is a regression test worth adding to this library, considering that it could realistically only catch a regression to a specific hashtable implementation with a specific hashing function, which is likely to end up being obsolete if people start to act on the issue in the unordered-containers library (haskell-unordered-containers/unordered-containers#319)?

**Comment by phadej** [comment]
@juhp 

> (I think it would be interesting to see any benchmark comparison(s) of 1.5 and 2.0 anyway)

See #883
